### ISSUE TITLE
Quiz URL

### ISSUE THREAD

**Issue by egy1st** [stevecopley/quiz#3]
I am not a guru in JavaScript, but I wonder if each quiz can have a unique URL i.e  https://stevecopley.github.io/quiz/python/q1

**Comment by stevecopley** [comment]
This would need the server configuring to ignore the sub-directories within the URL, i.e. the '/python/q1' part, so that it always served up the same page from the server root regardless of the URL. This is possible (e.g. via URL Rewrite rules in apache). But it's not possible just at the client side via browser JS.
